name: '自动同步上游仓库'
on:
  schedule:
    - cron: '0 2 * * *'  # 每天UTC时间2点（北京时间10点）运行，可根据需要调整
  workflow_dispatch:       # 允许在GitHub页面上手动触发工作流

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 同步上游变更
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: 'main'                 # 你希望更新的分支，例如main或master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: 'original-owner/original-repo'  # 替换为上游仓库地址，如torvalds/linux
          upstream_sync_branch: 'main'               # 上游仓库的分支名
          # test_mode: 'false'                       # 非测试模式，正式同步

      - name: 输出同步结果
        run: echo "同步完成"
